repos:
  - repo: git@github.com:astral-sh/ruff-pre-commit.git
    # Ruff version.
    rev: v0.11.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix, --config, ruff.toml ]
      # Run the formatter.
      - id: ruff-format
        args: [ --config, ruff.toml ]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.396
    hooks:
    - id: pyright